### ISSUE TITLE
CVE-2015-6616 

### ISSUE THREAD

**Issue by egmazur** [nowsecure/android-vts#112]
Hi guys,

I work with AOSP kitkat and some time ago (I think it was the middle of January) I decided to apply December security patches. And there were problems with applying ANDROID-24630158 patch to kitkat aosp version since code difference was very large. 
I decided to postpone this work. I got back to it in 3 weeks and I saw that google changed the original commit for ANDROID-24630158 to another one. This new commit cherry-picked real nice, without any problems.
But android-vts still shows that there is a cve-2015-6616 in my aosp code. And it shows old commit in description in cve-2015-6616.

The old commit is [here](https://android.googlesource.com/platform%2Fframeworks%2Fav/+/77c185d5499d6174e7a97b3e1512994d3a803151).
The new commit is [here](https://android.googlesource.com/platform%2Fframeworks%2Fav/+/257b3bc581bbc65318a4cc2d3c22a07a4429dc1d).

So what could it be? Exploit is not valid? The new patch doesn't fix vulnerablity? Or I just applied them improperly?

**Comment by Fuzion24** [comment]
Google hasn't been doing a 1 to 1 matching of bug to CVE
In many cases, CVEs contain a handful of different bugs, it is likely you patched for one or some, but not all.

It is also generally not recommended to backport/cherry-pick patches.  Many bug fixes are silently fixed with no security attribution. if at all possible, try to forward port your work rather than backporting google fixes.

**Comment by egmazur** [comment]
There is a list of commits in the description of CVE-2015-6616 in VTS for Android. So is it just a description?
One more detail: the old commit actually "fixes" the vulnerability, I mean, VTS for Android marked device as "CVE-2015-6616 free".

**Comment by egmazur** [comment]
Ah, just looked into VTS code for checking CVE-2015-6616. As I understood just presence of logs is checked, right? That explains a lot.
