### ISSUE TITLE
"Test is hanging"

### ISSUE THREAD

**Issue by Rikk** [nowsecure/android-vts#48]
Hi, I would like to know what means/what causes the "Test is hanging" result. Even with that, does it still means the device is not affected (green result)?

![screenshot_2015-11-11-00-46-30](https://cloud.githubusercontent.com/assets/2916485/11082649/391951e8-880e-11e5-804e-298d77ce5111.png)

**Comment by Fuzion24** [comment]
@Rikk  if you re-run does it give you the same result?

**Comment by Rikk** [comment]
Yes

**Comment by Fuzion24** [comment]
but if you run the scan multiple times, does it consistently say that?

**Comment by Rikk** [comment]
Yes, ran more than 5 times, each one the same.

**Comment by Fuzion24** [comment]
Some of the tests require permissions.  Pingpong root is a kernel bug related to sockets.. the app wouldn't be able to test for this bug without creating a socket(s).

**Comment by l00ping** [comment]
Hi, I get this message also at the same vulnerability and at 2 others. And in addition an error with CVE-2015-3825. Please note the exported results in the attachment. 
I own a 2 year old Samsung tablett Note 10.1

Btw. Thanks for this very useful app!
[Memo_20151115_182028.pdf](https://github.com/nowsecure/android-vts/files/34933/Memo_20151115_182028.pdf)

**Comment by Rikk** [comment]
Does [v.9](https://github.com/nowsecure/android-vts/releases/tag/v.9) fixes this, or reduces occurrence? I can't see the Apk in releases...

**Comment by Fuzion24** [comment]
Thank you for reminding me. v.9 release includes the apk now. 

I thought this issue may have been related to : #39  ... it is not.  That was a race condition in the checking code.

To give you a better understanding of what may be happening here:
The way the stagefright checks work are by creating a child process and actually trying to have android parse/play the media file.  In most cases, attempting to play one of these media files hits the appropriate bug and causes memory corruption usually causing crash.  Then the monitoring process just looks at the child to see if it crashed.  If it did, we know the device is vulnerable. However, there is no definitive way to assure that memory is corrupted in a consistent way that would cause a crash. In your case it's pretty likely that this bug is corrupting memory in such a way that it's causing an infinite loop inside the child process.  In this case, the particular test just hangs... at least until the monitoring parent realizes that it is past a certain timeout threshold and kills it.

I hope this makes sense.

Cheers,
Ryan

**Comment by Rikk** [comment]
Yes, thanks for the great explanation. Is that timeout something you can control? Is there any way to increase that timeout so we some extra confidence this is the case? Might the timeout be too small for all devices to handle whatever is requested properly?

**Comment by Fuzion24** [comment]
It's a couple of seconds.. The amount of data that the media processing code is parsing is sooo small that it should complete in a few ms...

**Comment by Rikk** [comment]
Okay
The new version looks great, the colors and descriptions are much better than before.
And now I know I'm vulnerable to CVE-2015-6608 omg lol. (At least that's the only one -- not counting the always-hanging one)

**Comment by Fuzion24** [comment]
Thanks.  Which device / model / version do you have?  

You should consider a nexus device ;-)

**Comment by Rikk** [comment]
It's a simple SM-G360M ('Core Prime' or 'Win 2 Duos'), enough for my mobile needs :)
Here we pay more than 4 times what US people pay for phones...

[vts-v9-results.txt](https://github.com/nowsecure/android-vts/files/38505/vts-v9-results.txt)
Btw, in the report, imo 'versionName' and 'versionCode' would better not be together with phone info as they refer to VTS and not to the phone...

**Comment by Fuzion24** [comment]
Duly noted

**Comment by l00ping** [comment]
I ran the test with the version. 9 Unfortunately, the same error messages.
![screenshot_2015-11-19-22-07-35](https://cloud.githubusercontent.com/assets/15859645/11284646/476c65ec-8f0b-11e5-93e5-189bfb96e933.png)
