### ISSUE TITLE
Suggestions, Feature Requests, Bug Reports & Questions

### ISSUE THREAD

**Issue by Shakil-Shahadat** [nowsecure/android-vts#75]
## Look and Feel Suggestions

- Place the name with logo at the top

- Front page needn't to be scroll able. 

- On the front page, only a focused device info with a soothing background and a bigger centered 'scan' button might look good and symmetric. Current scan button looks asymmetric, i think this button should have more attention as that's what the most users gonna look first when they start the app.

- Change 'Not vulnerable' to 'Safe', 'Error running test' to just 'Error'. Less word, more readability.

- Group vulnerabilities according to Vulnerable / Error / Safe along with their number. And show the details button where vulnerability status is shown now. This will reduce vertical space as well as give users an easy glimpse of system vulnerability status. Here is a rough sketch of what I mean.
![sketch for vts](https://cloud.githubusercontent.com/assets/8978625/11321463/96a2a1a4-90ea-11e5-9c34-933a8df0cb87.png)

- Place test failing explanation under the vulnerability name or under vulnerability description.

- Show scroll bar in the result page.

## Feature Requests

- Show the number of vulnerability it can detect on the front page. Show how many of them applies to the current device and Android version and run only those tests. For example, CVE-2015-7888 is only applicable for Android 5.0+, Samsung devices only. This test is failing on my Samsung Galaxy S2 with Android 4.1.2. I think this will reduce number of 'error running the test' cases.

- Show vulnerability critical level based on how easily they can be exploited, the history of exploitation, how much damage it can do etc if possible.

- Vulnerabilities could be organised according to their date of release.

- Allow sharing data directly from the app instead of google form. Add a check mark to ask for user consent to send the analysis data automatically. Also mention that if auto data sending is enabled at the end of the scan report. I hope this data will help visualize how vulnerable the android ecosystem is.

- Please add explanation about what data are sent. Explain if it sends device info too and if the device / related google account is tracked.

- Save scan results. And allow comparing them with the latest one, and if anything has changed let the user know.

- Periodical / scheduled scanning and reporting.

## Bug Report

- Typo in the details of all of the 'ZipBug', CVE-2013-6282, CVE-2014-3153, CVE-2015-1528, CVE-2015-3825 vulnerabilities 'Impact' section. 'privilidges' should be 'privileges'. It may be in other places too, I may have missed.

- Typo in the details of CVE-2015-7888 vulnerabilities 'Impact' section. 'brows' should be 'browse'.

## Questions

- You mentioned, 'VTS will choose the most critical vulnerabilities (that are reasonable to check for) and include these checks shortly after the security bulletin is released.' But what about the old vulnerabilities? I hope you try to be as comprehensive as possible if that is not a headache for you.

- Will you gonna publish user submitted data? If so, how and when? What is your plan about the data?

Also thanks for making this app.

**Comment by Fuzion24** [comment]
UX/UI Suggestions:

I'll mostly defer to @SandroMachado here as he's been doing a great job with the UI/UX.  If you feel strongly enough to contribute, pull requests are welcome. 

I do, however, disagree with replacing not vulnerable to safe.  I think this gives the wrong impression.

I think for now we should stay way from grouping as well.  We have been able to close the gap here a bit by ordering the checks by date.

Feature Requests:
1) I opened an issue for this https://github.com/nowsecure/android-vts/issues/77
2) The criticality of the vulnerability is in the more details section.. this is what the cvss2 score represents
3) Done here: https://github.com/nowsecure/android-vts/pull/76
4) We wanted to avoid doing this as it would have the application posting data directly to one of our endpoints.  In order to keep the application as open as possible, we decided against this.
5) Feel free to look over the source to see what all is sent.  You can also share to yourself to view this info.  Device information is collected, but no unique identifiers.  Nothing related to your Google (or any other) account is collected.
6) This is what the export/share feature is for.
7) Done here: https://github.com/nowsecure/android-vts/pull/71

Bug reports:
Fixed here: https://github.com/nowsecure/android-vts/pull/74

Questions:
Older vulnerabilities will continued to be checked as well, as regressions could happen.
The data that is collected is freely available here: https://docs.google.com/spreadsheets/d/1HP9zlk5DlSaSRx0mmml_-XBFMq2ICso_5fHIDRyrqT8/edit#gid=1156113454

Cheers,
Ryan

**Comment by Shakil-Shahadat** [comment]
Hi, thanks for the reply. I actually didn't mistrust you at all. Rather I liked your openness and that's why hoped for more in a positive way. I didn't find what kind of data is being collected anywhere. I even shared my data before asking what I was sharing. I just asked permission to view the data.

I wish I knew android programming. If I learn, I will definitely send you pull request.

You have been doing a great job. Thanks for your effort.

**Comment by Fuzion24** [comment]
:+1:

**Comment by SandroMachado** [comment]
@Shakil-Shahadat thanks for your suggestions.

>Place the name with logo at the top 

The name is already there, I will try to put the logo and if it works fine with the collapsing layout I will create a PR with that change. 

>Front page needn't to be scroll able.

>On the front page, only a focused device info with a soothing background and a bigger centered 'scan' button might look good and symmetric. Current scan button looks asymmetric, i think this button should have more attention as that's what the most users gonna look first when they start the app.

In devices with bigger screens this is a waste of space, and a screen with just a button and a some information that is not useful for most part of the users, IMO, it is not a good usability approach. This will also lead to more user interactions to rerun the tests and go back to the device information.

> Change 'Not vulnerable' to 'Safe', 'Error running test' to just 'Error'. Less word, more readability.

>Group vulnerabilities according to Vulnerable / Error / Safe along with their number. And show the details button where vulnerability status is shown now. This will reduce vertical space as well as give users an easy glimpse of system vulnerability status. Here is a rough sketch of what I mean.

Fuzion24 already replied. 

>Place test failing explanation under the vulnerability name or under vulnerability description.

Hum, usually the explanation of the failure is not relevant for the user, it is just a programming exception or an implementation bug. 

>Show scroll bar in the result page

Usually with the `Cards UI` there are no scrollbars, the users have the perception that the content is scrollable. See apps like Facebook or Google Plus.

Thanks again for the suggestions.
